### ISSUE TITLE
How do I initialize this editor in my project?

### ISSUE THREAD

**Issue by jrdn91** [lukebrenton/ember-cli-medium-editor#1]
After installing and adding that bit to the jshint file what do I do from there? I still don't understand how to add it to my project, some guidance here would be great.

**Comment by e-karma** [comment]
Thanks for making this Luke!! Very excited to implement this as it's exactly what i've been looking to add (contentEditable) and am glad I came across this first.

+1 on the 'next-steps' however after install...

Thanks!

**Comment by lukebrenton** [comment]
I've just updated the github readme with an example - Let me know if that helps!
