### ISSUE TITLE
ES6 syntax not transpiling

### ISSUE THREAD

**Issue by fotinakis** [lukebrenton/ember-cli-medium-editor#11]
Right now, this addon causes untranspiled ES6 syntax to be incorporated into host applications, potentially breaking them. Specifically, the `const { computed, observer } = Ember;` line is not transpiled:

<img width="454" alt="screen shot 2016-05-27 at 1 37 50 pm" src="https://cloud.githubusercontent.com/assets/75300/15622813/a60d5fba-2421-11e6-8de8-66e8603300e2.png">

This may work without error on very new versions of Chrome, but will break everywhere else.

This is caused by the fact that the addon does not depend on `ember-cli-babel` in package.json. Simply adding this to `package.json` will fix it:

```javascript
  "dependencies": {
    "ember-cli-babel": "^5.1.5"
  },
```

Thanks!

**Comment by lukebrenton** [comment]
Thanks @fotinakis. Added! :)
