### ISSUE TITLE
Provide a callback that indicates that the user finished typing

### ISSUE THREAD

**Issue by ddoria921** [lukebrenton/ember-cli-medium-editor#13]
Right now there is no way to know if the user finished typing.

A common use case for this would be if you want to track how long the user has been active or maybe you want to trigger an action (like a save) as soon as the user is done typing.

My proposed solution – a parameter that accepts an action:
`{{medium-content-editable value=model.text options=editorOptions onFinishedTyping=(action "saveContent")}}`

**Comment by ddoria921** [comment]
Working on this now.

**Comment by lukebrenton** [comment]
Hi @ddoria921 Nice work! I've merged it in.

**Comment by ddoria921** [comment]
Thanks! :)
