### ISSUE TITLE
disableEditing fails to prevent editing

### ISSUE THREAD

**Issue by jarrodzimm** [lukebrenton/ember-cli-medium-editor#16]
It looks like `contenteditable` is remaining `true` even when `disableEditing` is `true` in the options. I'm not sure where this is being set in the lifecycle.

```
readOnlyOptions: {
  disableEditing: true
}
```
```
{{medium-content-editable value=text options=readOnlyOptions}}
```

If I use...
```
var editor = new MediumEditor('.editor', {
    disableEditing: true
});
```
...instead to initialize a new editor, `disableEditing` works as expected.

Thoughts?

**Comment by jarrodzimm** [comment]
Ah, I see you have an `editable` option of your own. That works well.

**Comment by mnifakram** [comment]
@jarrodz it didn't worked for me

`{{medium-content-editable
  value=editorValue
  options=options
  insertOptions=insertOptions
  onFinishedTyping=(action 'onFinishedTyping')
  editable=false
}}`

any idea what would be the problem?

**Comment by jarrodzimm** [comment]
Unfortunately, I don't. I've been away from this project for too long.
