### ISSUE TITLE
Ember v2.0 compatibility

### ISSUE THREAD

**Issue by ianbale** [lukebrenton/ember-cli-medium-editor#4]
I'm just giving this a test out to decide whether to make use of it in a new project or not.  I'm seeing the following warning (with Ember 1.13.9 on Ember-CLI 1.13.3):

Using a custom `.render` function is deprecated and will be removed in Ember 2.0.0. [deprecation id: ember-views.render]

Any plans to update this this control to be Ember v2.0 compatible? If so, do you have an ETA?

**Comment by lukebrenton** [comment]
Hi @ianbale. Probably a bit late now but the deprecation warning has been fixed.
